INFO level - 2024-01-15 15:14:47,280 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:14:57,973 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:14:58,474 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:15:05,598 shopapp.views: "Logging for info-level is set"
INFO level - 2024-01-15 15:16:23,689 shopapp.views: "Logging for info-level is set"
INFO level - 2024-01-15 15:25:42,697 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:25:43,231 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:25:53,872 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:25:54,332 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:26:05,836 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:26:06,337 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:26:24,286 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:26:24,787 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:26:38,611 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:26:39,065 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:26:45,603 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:26:46,169 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:26:50,663 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:26:51,101 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:27:01,788 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:27:02,285 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:27:10,878 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:27:11,384 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:27:16,898 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:27:17,405 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:28:07,109 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:28:07,572 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:28:11,011 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:29:13,722 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:29:47,362 shopapp.views: "Logging for info-level is set"
ERROR level - 2024-01-15 15:29:47,762 django.request: "Internal Server Error: /ru/shop/"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\debug_toolbar\middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\debug_toolbar\toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
INFO level - 2024-01-15 15:30:34,314 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-15 15:30:34,844 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:31:30,248 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\urls.py changed, reloading."
INFO level - 2024-01-15 15:31:30,718 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:31:50,709 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\urls.py changed, reloading."
INFO level - 2024-01-15 15:31:51,274 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:31:56,769 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\urls.py changed, reloading."
INFO level - 2024-01-15 15:31:57,258 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:32:09,874 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\urls.py changed, reloading."
INFO level - 2024-01-15 15:32:10,349 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:32:19,826 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\urls.py changed, reloading."
INFO level - 2024-01-15 15:32:20,286 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:32:59,840 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 15:33:03,206 shopapp.views: "Logging for info-level is set"
INFO level - 2024-01-15 23:12:16,551 django.utils.autoreload: "Watching for file changes with StatReloader"
WARNING level - 2024-01-15 23:12:19,590 django.request: "Not Found: /"
INFO level - 2024-01-15 23:13:10,480 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-15 23:13:11,212 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 23:13:17,062 shopapp.views: "Logging for info-level is set"
ERROR level - 2024-01-15 23:13:17,121 django.request: "Internal Server Error: /ru/shop/"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py", line 47, in shop_index
    print(1/0)
          ~^~
ZeroDivisionError: division by zero
INFO level - 2024-01-15 23:13:33,672 shopapp.views: "Logging for info-level is set"
ERROR level - 2024-01-15 23:13:33,745 django.request: "Internal Server Error: /ru/shop/"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py", line 47, in shop_index
    print(1/0)
          ~^~
ZeroDivisionError: division by zero
INFO level - 2024-01-15 23:14:42,913 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-15 23:14:43,589 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-15 23:15:05,925 shopapp.views: "Logging for info-level is set"
INFO level - 2024-01-15 23:19:57,021 shopapp.views: "Logging for info-level is set"
INFO level - 2024-01-18 14:41:18,982 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 14:49:28,656 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 14:56:20,826 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 15:00:43,470 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\settings.py changed, reloading."
INFO level - 2024-01-18 15:00:44,349 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 15:01:35,828 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\mysite\urls.py changed, reloading."
INFO level - 2024-01-18 15:01:36,914 django.utils.autoreload: "Watching for file changes with StatReloader"
WARNING level - 2024-01-18 15:01:39,441 django.request: "Not Found: /"
ERROR level - 2024-01-18 15:01:51,645 django.request: "Internal Server Error: /sitemap.xml"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 187, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 122, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 92, in _get
    return attr(item)
           ^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 132, in location
    return item.get_absolute_url()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py", line 27, in get_absolute_url
    return reverse('shopapp:product_detail')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product_detail' with no arguments not found. 1 pattern(s) tried: ['ru/shop/products/(?P<pk>[0-9]+)/\\Z']
INFO level - 2024-01-18 15:03:58,167 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py changed, reloading."
INFO level - 2024-01-18 15:03:59,024 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 15:04:07,627 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py changed, reloading."
INFO level - 2024-01-18 15:04:08,332 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 15:04:45,086 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py changed, reloading."
INFO level - 2024-01-18 15:04:45,886 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 15:06:45,229 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py changed, reloading."
INFO level - 2024-01-18 15:06:46,124 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-18 15:06:46,799 django.request: "Internal Server Error: /sitemap.xml"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 187, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 122, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 92, in _get
    return attr(item)
           ^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py", line 15, in location
    return reverse(item)
           ^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'orders_list' not found. 'orders_list' is not a valid view function or pattern name.
ERROR level - 2024-01-18 15:06:48,387 django.request: "Internal Server Error: /sitemap.xml"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 187, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 122, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 92, in _get
    return attr(item)
           ^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py", line 15, in location
    return reverse(item)
           ^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'orders_list' not found. 'orders_list' is not a valid view function or pattern name.
INFO level - 2024-01-18 15:06:56,333 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py changed, reloading."
INFO level - 2024-01-18 15:06:57,264 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 15:20:40,171 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py changed, reloading."
INFO level - 2024-01-18 15:20:41,036 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:28:29,090 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py changed, reloading."
INFO level - 2024-01-18 16:28:30,170 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:28:37,699 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py changed, reloading."
INFO level - 2024-01-18 16:28:38,418 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:29:53,513 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\models.py changed, reloading."
INFO level - 2024-01-18 16:29:54,193 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:33:18,883 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py changed, reloading."
INFO level - 2024-01-18 16:33:19,679 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-18 16:33:21,504 django.request: "Internal Server Error: /sitemap.xml"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: shopapp_product.updated_at

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 167, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\sitemaps\__init__.py", line 186, in _urls
    for item in paginator_page.object_list:
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: shopapp_product.updated_at
INFO level - 2024-01-18 16:46:08,374 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\sitemap.py changed, reloading."
INFO level - 2024-01-18 16:46:09,103 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:54:55,560 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:54:56,540 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:55:01,052 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:55:01,740 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:55:05,067 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:55:05,841 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:55:10,324 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:55:11,018 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:55:14,551 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:55:15,169 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:58:00,223 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:58:01,004 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 16:59:56,274 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 16:59:57,081 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:00:41,034 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\urls.py changed, reloading."
INFO level - 2024-01-18 17:00:41,753 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:01:33,623 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\urls.py changed, reloading."
INFO level - 2024-01-18 17:01:34,398 django.utils.autoreload: "Watching for file changes with StatReloader"
WARNING level - 2024-01-18 17:02:00,079 django.request: "Not Found: /ru/shop/products/latest/feed"
INFO level - 2024-01-18 17:02:20,474 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\urls.py changed, reloading."
INFO level - 2024-01-18 17:02:21,437 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-18 17:02:21,962 django.request: "Internal Server Error: /ru/shop/products/latest/feed"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LatestProductsFeed() takes no arguments
INFO level - 2024-01-18 17:02:46,801 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\urls.py changed, reloading."
INFO level - 2024-01-18 17:02:47,649 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-18 17:02:48,283 django.request: "Internal Server Error: /ru/shop/products/latest/feed"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\syndication\views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\syndication\views.py", line 143, in get_feed
    link = add_domain(current_site.domain, link, request.is_secure())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\contrib\syndication\views.py", line 17, in add_domain
    if url.startswith("//"):
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
INFO level - 2024-01-18 17:04:02,899 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 17:04:03,842 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:04:31,169 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\views.py changed, reloading."
INFO level - 2024-01-18 17:04:32,056 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:06:40,167 django.utils.autoreload: "Watching for file changes with StatReloader"
WARNING level - 2024-01-18 17:06:42,186 django.request: "Not Found: /"
INFO level - 2024-01-18 17:06:48,097 shopapp.views: "Logging for info-level is set"
WARNING level - 2024-01-18 17:08:09,783 django.request: "Not Found: /ru/shop/latest/feed"
INFO level - 2024-01-18 17:16:10,106 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\forms.py changed, reloading."
INFO level - 2024-01-18 17:16:10,786 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:17:25,510 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\forms.py changed, reloading."
INFO level - 2024-01-18 17:17:26,134 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:19:43,359 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-18 17:19:44,033 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:22:10,578 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-18 17:22:11,228 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-18 17:48:10,716 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-18 17:48:11,621 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 16:53:19,602 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 16:53:20,489 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 17:10:35,710 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 17:10:36,485 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 17:10:42,146 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 17:10:42,882 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 17:11:45,052 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 17:11:45,883 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 17:12:50,376 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view shopapp.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
INFO level - 2024-01-19 17:13:49,015 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 17:13:49,889 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 17:13:51,058 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view shopapp.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
INFO level - 2024-01-19 17:14:34,808 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 17:14:35,751 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 18:01:40,333 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 18:01:41,189 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 18:01:44,561 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 18:01:45,266 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 18:01:52,981 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 18:01:53,723 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 18:02:58,382 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 18:02:59,108 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 18:04:35,230 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 18:04:35,978 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:01:22,308 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:01:23,217 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 19:02:02,331 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 69, in import_as_CSV
    users = User.objects.value('username').all()
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'UserManager' object has no attribute 'value'
INFO level - 2024-01-19 19:02:15,397 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:02:16,160 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:05:27,146 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:05:27,825 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:09:16,776 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:09:17,380 django.utils.autoreload: "Watching for file changes with StatReloader"
WARNING level - 2024-01-19 19:09:29,093 django.request: "Not Found: /ru/admin/shopapp/import-csv"
INFO level - 2024-01-19 19:13:01,777 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:13:02,462 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:14:12,192 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:14:12,846 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:22:08,797 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:22:09,491 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:24:24,535 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:24:25,221 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:42:24,688 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:42:25,413 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:51:18,016 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:51:18,634 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 19:56:01,654 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 19:56:02,282 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 20:11:57,784 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:11:58,423 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 20:13:53,124 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:13:53,835 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 20:34:07,222 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:34:08,473 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 20:35:45,607 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 94, in import_as_CSV
    self.message_user(request, message=f'Orders in row/rows #{", ".split(unsuccessful)} were not uploaded. \n'
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be str or None, not list
INFO level - 2024-01-19 20:36:18,672 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:36:19,586 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 20:36:20,891 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 94, in import_as_CSV
    self.message_user(request, message=f'Orders in row/rows #{", ".join(unsuccessful)} were not uploaded. \n'
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
INFO level - 2024-01-19 20:36:52,247 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:36:53,157 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 20:36:54,334 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 90, in import_as_CSV
    unsuccessful = ", ".join(import_orders_from_csv(csv_file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
ERROR level - 2024-01-19 20:37:11,923 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 90, in import_as_CSV
    unsuccessful = ", ".join(import_orders_from_csv(csv_file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
INFO level - 2024-01-19 20:38:29,139 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:38:30,037 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 20:41:24,695 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:41:25,460 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 20:41:42,483 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:41:43,244 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 20:42:24,015 django.request: "Internal Server Error: /ru/admin/shopapp/order/import-csv"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 96, in import_as_CSV
    unsuccessful = import_orders_from_csv(csv_file)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py", line 22, in import_orders_from_csv
    for row in DictReader(csv_file):
  File "C:\Python311\Lib\csv.py", line 110, in __next__
    self.fieldnames
  File "C:\Python311\Lib\csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
                       ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 624: character maps to <undefined>
INFO level - 2024-01-19 20:46:10,855 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 20:46:11,599 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 21:00:44,694 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 21:00:45,444 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 21:00:57,404 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 21:00:58,205 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 21:13:42,174 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 21:13:43,013 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 22:32:43,143 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 22:32:43,918 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 22:35:02,157 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 22:35:02,847 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 22:35:10,471 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 22:35:11,097 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 22:35:17,466 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 22:35:18,057 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 22:35:21,538 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 22:35:22,183 django.utils.autoreload: "Watching for file changes with StatReloader"
INFO level - 2024-01-19 22:35:37,024 django.utils.autoreload: "C:\Users\kurba\PycharmProjects\AnotherDjango\python_django\mysite\shopapp\admin.py changed, reloading."
INFO level - 2024-01-19 22:35:37,632 django.utils.autoreload: "Watching for file changes with StatReloader"
ERROR level - 2024-01-19 22:42:02,342 django.request: "Internal Server Error: /ru/admin/shopapp/order/"
Traceback (most recent call last):
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\sentry_sdk\integrations\django\templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kurba\PycharmProjects\AnotherDjango\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'imprt_csv' not found. 'imprt_csv' is not a valid view function or pattern name.
INFO level - 2024-01-19 22:43:12,538 shopapp.views: "Logging for info-level is set"
